### ISSUE TITLE
Prepare for prod (meta)

### ISSUE THREAD

**Issue by shinyfoil** [geometry-labs/icon-explorer#55]
## Repo prep
- [x] https://github.com/geometry-labs/icon-blocks/issues/98
- [x] https://github.com/geometry-labs/icon-logs/issues/40
- [x] https://github.com/geometry-labs/icon-transactions/issues/72
- [x] https://github.com/geometry-labs/icon-governance/issues/6
- [x] https://github.com/geometry-labs/icon-accounts/issues/21
- [x] https://github.com/geometry-labs/icon-tracker-frontend/issues/80
- [x] https://github.com/geometry-labs/icon-contracts/issues/7
- [x] https://github.com/geometry-labs/icon-etl/issues/23

## DB prep
- [x] Deploy ETL
- [x] Deploy Kakfa cluster
- [x] Deploy Redis instance
- [x] Deploy PG cluster
  - [ ] Configure WAL backups

## First release
Push first tagged releases for
- [x] blocks
- [x] logs
- [x] transactions
- [x] governance
- [x] accounts
- [x] contracts
- [x] frontend
